### ISSUE TITLE
Support Go 1.18

### ISSUE THREAD

**Issue by zhsj** [bradfitz/shotizam#13]
When analyze binaries built by go1.18beta2, I get:

```
$ shotizam --sqlite ./build/api 
not a go1.2+ line table
```

**Comment by josharian** [comment]
Why does this repo copy/paste in package gosym, instead of using std debug/gosym?

**Comment by bradfitz** [comment]
> Why does this repo copy/paste in package gosym, instead of using std debug/gosym?

It's a fork with extra API, IIRC.

**Comment by josharian** [comment]
Got it. Unfortunately, step one will be rebasing/recreating that extra API based on the new debug/gosym, because the underlying data format changed a lot as part of my linker work.

**Comment by Splizard** [comment]
The functions required are
`(t *Table) PtrSize() int`
`(f *Func) TableSizePCSP() int`
`(f *Func) TableSizePCFile() int`
`(f *Func) TableSizePCLn() int`

**Comment by bradfitz** [comment]
@Splizard, interested in fixing this? :)

**Comment by brycekahle** [comment]
Should be fixed with #15

**Comment by kashav** [comment]
FYI, the PR for this was accepted a while back. Is there any reason to keep this issue around?

**Comment by bradfitz** [comment]
Nope! Closing. Thanks for the reminder.
