### ISSUE TITLE
Alternatives?

### ISSUE THREAD

**Issue by AlekSi** [bradfitz/shotizam#5]
How that compares to https://github.com/jondot/goweight and https://github.com/zboya/gobinsize?

**Comment by foxcpp** [comment]
And also to https://github.com/foxcpp/golf!

(shameless self-promotion)

**Comment by foxcpp** [comment]
gobinsize, gosize and my utility seem to be mostly similar - they parse symbol table from the executable and try to group symbols by Go package. goweight works differently, as described in https://github.com/foxcpp/golf#golf-vs-goweight: goweight parses objects go toolchain leaves in /tmp/go-build-XXXXXXX, object files there are already conveniently grouped by package so it just reads their total FS size and extracts package name from them.

**Comment by bradfitz** [comment]
I hadn't heard of any of these.

**Comment by bradfitz** [comment]
I can no answer this in a satisfying way: shotizam (the new name of this repo/tool) is different in that it doesn't shell out to another program, and it parses the Go pclntab metadata completely to actually understand all the metadata overhead.

And it can output SQLite for analysis.
